version: '2'

services:
  backend:
    environment:
      - SSL=true
      - SSL_KEY=/app/certs/server.key
      - SSL_CERT=/app/certs/server.crt
    build: ./Backend
    restart: unless-stopped
    container_name: backend
    ports:
      - 3000:3000

  frontend:
    environment:
      - BACKEND_URL=https://51.83.129.128:3000
      - PORT=8080
      - SSL=true
      - SSL_KEY=/app/certs/server.key
      - SSL_CERT=/app/certs/server.crt
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    build: ./frontend
    container_name: frontend
    ports:
      - 8080:8080
